steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/fiery-chess-357609/firealarm/firealarm-test:$COMMIT_SHA', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-south1-docker.pkg.dev/fiery-chess-357609/firealarm/firealarm-test:$COMMIT_SHA']
 
logsBucket: 'gs://firealarm-log'
    options:
      logging: GCS_ONLY
