steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia.gcr.io/fiery-chess-357609/firealarm/firealarm-pd', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia.gcr.io/fiery-chess-357609/firealarm/firealarm-pd']
